import Navbar from "@/components/Navbar";
import "./globals.css";
import Providers from "./providers";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full antialiased">
      <body className="min-h-full flex flex-col" cz-shortcut-listen="true">
        <Providers>
        <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
